[build]
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "22"
PLAYWRIGHT_BROWSERS_PATH = "0"

[[redirects]]
from = "/2025/hksiam/*"
to = "/2025/hksiam/index.html"
status = 200
