packages:
  - '*/src'

catalog:
  '@antfu/eslint-config': ^4.16.2
  '@eslint-react/eslint-plugin': ^1.52.2
  '@eslint/config-inspector': ^1.1.0
  '@iconify/collections': ^1.0.567
  '@iconify/json': ^2.2.357
  '@slidev/cli': ^51.8.2
  '@slidev/client': ^51.8.2
  '@slidev/theme-default': ^0.25.0
  '@types/node': ^24.0.13
  '@types/prompts': ^2.4.9
  '@types/seedrandom': ^3.0.8
  chroma-js: ^3.1.2
  eslint: ^9.30.1
  eslint-config-flat-gitignore: ^2.1.0
  eslint-plugin-format: ^1.0.1
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  eslint-typegen: ^2.2.1
  esno: ^4.8.0
  execa: ^9.6.0
  fast-glob: ^3.3.3
  markdown-it-magic-link: ^0.1.4
  playwright-chromium: ^1.54.0
  pnpm: ^10.13.1
  prettier-plugin-slidev: ^1.0.5
  prompts: ^2.4.2
  rimraf: ^6.0.1
  seedrandom: ^3.0.5
  slidev-addon-graph: ^0.1.1
  taze: 19.1.0
  typescript: ^5.8.3
  unocss: ^66.3.3
  uqr: ^0.1.2
  vis-data: ^7.1.10
  vis-network: ^9.1.13
  vis-timeline: ^7.7.4
  vite: ^6.3.5
  vue-router: ^4.5.1
  vue-tsc: ^2.2.12

onlyBuiltDependencies:
  - esbuild
  - playwright-chromium
  - unrs-resolver
